import Head from "next/head";
import Layout from "@/components/layout/Layout";
import uuid from "react-uuid";
import ShowCard from "@/components/ShowCard";
import axios from "axios";
import { useRouter } from "next/router";
import Error from "next/error";

export default function Genre({ currentGenreCollection }) {
  const router = useRouter();
  if (!router.isFallback && !currentGenreCollection) {
    return <Error statusCode={404} />;
  }
  const { currentGenreTVSeries, title } = currentGenreCollection;
  return (
    <>
      <Head>
        <title>{`${title} TV Series | EntertainHub`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <Layout category="tvseries">
        <div className="showListContainer">
          <div className="sectionWrapper">
            <h1 className="headingContainer | padding-inline fs-l-primary-heading fw-light">
              {title}{" "}
              <span className="categoryBlock | fs-m-body fw-regular">
                TV Series
              </span>
            </h1>
            <div className="showCardContainer | padding-inline padding-block-top padding-block-bottom">
              {currentGenreTVSeries.map((item) => (
                <ShowCard show={item} key={uuid()} />
              ))}
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}

export async function getStaticPaths() {
  const tvSeriesGenreEndpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT}/tvseries/genre`;
  const { data } = await axios.get(tvSeriesGenreEndpoint);

  const paths = data.genres.map((item) => ({
    params: {
      genreId: item.id,
    },
  }));

  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps(context) {
  const genreId = context.params.genreId;
  return {
    props: {
      currentGenreCollection: await getCurrentGenreShows(genreId),
    },
  };
}

async function getCurrentGenreShows(genreId) {
  const tvShowsEndpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT}/tvseries/genre/${genreId}`;
  const { data } = await axios.get(tvShowsEndpoint);
  return data;
}
