import Head from "next/head";
import Layout from "@/components/layout/Layout";
import TvSeriesContainer from "../../components/tv-series/TvSeriesContainer";
import axios from "axios";

export default function TvSeries({ shows }) {
  const { tvSeries: tvSeriesData } = shows;

  return (
    <>
      <Head>
        <title>TV-series | EntertainHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <Layout>
        <TvSeriesContainer data={tvSeriesData} />
      </Layout>
    </>
  );
}

export async function getServerSideProps() {
  return {
    props: {
      shows: await getTvShows(),
    },
  };
}

async function getTvShows() {
  const tvShowsEndpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT}/tvseries`;
  const { data } = await axios.get(tvShowsEndpoint);

  return data;
}
