import Head from "next/head";
import { useShow } from "@/components/contextProviders/ShowProvider";
import Layout from "@/components/layout/Layout";
import ShowCard from "@/components/ShowCard";
import uuid from "react-uuid";

export default function TvSeries() {
  const { data } = useShow();
  const seriesCollection = data.filter((item) => item.category === "TV Series");

  return (
    <>
      <Head>
        <title>TV-series | EntertainHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <Layout>
        <div className="showListContainer">
          <div class="sectionWrapper">
            <h1 className="padding-inline fs-l-primary-heading fw-light">
              TV Series
            </h1>
            <div className="showCardContainer | padding-inline padding-block-top padding-block-bottom">
              {seriesCollection.map((item) => (
                <ShowCard show={item} key={uuid()} />
              ))}
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
