import Head from "next/head";
import Layout from "@/components/layout/Layout";
// import TvSeriesContainer from "../../components/tv-series/TvSeriesContainer";
import GenreContainer from "@/components/GenreContainer";
import axios from "axios";

export default function TvSeries({ genreList }) {
  const { genres } = genreList;
  return (
    <>
      <Head>
        <title>TV-series | EntertainHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <Layout>
        <GenreContainer data={genres} category="TV Series" />
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {
      genreList: await getTVSeriesGenreList(),
    },
  };
}

async function getTVSeriesGenreList() {
  const tvSeriesEndpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT}/tvseries/genre`;
  const { data } = await axios.get(tvSeriesEndpoint);
  return data;
}
