import React from "react";
import Head from "next/head";
import Layout from "@/components/layout/Layout";
import ShowCard from "@/components/ShowCard";
import axios from "axios";
import uuid from "react-uuid";

const NowPlaying = ({ shows }) => {
  const { nowPlayingShows } = shows;
  return (
    <>
      <Head>
        <title>Now Playing Movies | EntertainHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <Layout>
        <div className="showListContainer">
          <div className="sectionWrapper">
            <h1 className="padding-inline fs-l-primary-heading fw-light">
              Now Playing Movies
            </h1>
            <div className="showCardContainer | padding-inline padding-block-top padding-block-bottom">
              {nowPlayingShows.map((item) => (
                <ShowCard show={item} key={uuid()} />
              ))}
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default NowPlaying;

export async function getStaticProps() {
  return {
    props: {
      shows: await getNowPlayingShows(),
    },
  };
}

async function getNowPlayingShows() {
  const nowPlayingEndpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT}/movies/now_playing`;

  try {
    const res = await axios.get(nowPlayingEndpoint);
    const data = res.data;
    return data;
  } catch (err) {
    return { error: err };
  }
}
