import Head from "next/head";
import Layout from "@/components/layout/Layout";
import uuid from "react-uuid";
import ShowCard from "@/components/ShowCard";
import axios from "axios";

export default function Genre({ currentGenreCollection }) {
  const { currentGenreMovies, title } = currentGenreCollection;
  return (
    <>
      <Head>
        <title>{`${title} Movies | EntertainHub`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <Layout>
        <div className="showListContainer">
          <div className="sectionWrapper">
            <h1 className="padding-inline fs-l-primary-heading fw-light">
              {title} Movies
            </h1>
            <div className="showCardContainer | padding-inline padding-block-top padding-block-bottom">
              {currentGenreMovies.map((item) => (
                <ShowCard show={item} key={uuid()} />
              ))}
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}

export async function getStaticPaths() {
  const movieGenreEndpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT}/movies/genre`;
  const { data } = await axios.get(movieGenreEndpoint);

  const paths = data.genres.map((item) => ({
    params: {
      genreId: item.id,
    },
  }));

  return {
    paths,
    fallback: true,
  };
}

export async function getStaticProps(context) {
  const genreId = context.params.genreId;
  return {
    props: {
      currentGenreCollection: await getCurrentGenreShows(genreId),
    },
  };
}

async function getCurrentGenreShows(genreId) {
  const movieShowsEndpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT}/movies/genre/${genreId}`;
  const { data } = await axios.get(movieShowsEndpoint);
  return data;
}
