import React from "react";
import Head from "next/head";
import Layout from "@/components/layout/Layout";
import ShowCard from "@/components/ShowCard";
import axios from "axios";
import uuid from "react-uuid";

const TopRated = ({ shows }) => {
  const { topRatedShows } = shows;
  return (
    <>
      <Head>
        <title>Top Rated Movies | EntertainHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <Layout category="movies">
        <div className="showListContainer">
          <div className="sectionWrapper">
            <h1 className="headingContainer | padding-inline fs-l-primary-heading fw-light">
              Top Rated{" "}
              <span className="categoryBlock | fs-m-body fw-regular">
                Movie
              </span>
            </h1>
            <div className="showCardContainer | padding-inline padding-block-top padding-block-bottom">
              {topRatedShows.map((item) => (
                <ShowCard show={item} key={uuid()} />
              ))}
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default TopRated;

export async function getStaticProps() {
  return {
    props: {
      shows: await getTopRatedShows(),
    },
  };
}

async function getTopRatedShows() {
  const TopRatedEndpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT}/movies/top_rated`;

  try {
    const res = await axios.get(TopRatedEndpoint);
    const data = res.data;
    return data;
  } catch (err) {
    return { error: err };
  }
}
