import Head from "next/head";
import { useShow } from "@/components/context/ShowProvider";
import Layout from "@/components/layout/Layout";
import MovieContainer from "@/components/movies/MovieContainer";
import ShowCard from "@/components/ShowCard";
import uuid from "react-uuid";
import axios from "axios";

export default function Movies({ shows }) {
  const { movies: moviesData } = shows;
  return (
    <>
      <Head>
        <title>Movies | EntertainHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <Layout>
        <MovieContainer data={moviesData} />
      </Layout>
    </>
  );
}

export async function getServerSideProps() {
  return {
    props: {
      shows: await getTvShows(),
    },
  };
}

async function getTvShows() {
  const moviesEndpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT}/movies`;
  const { data } = await axios.get(moviesEndpoint);

  return data;
}
