import Head from "next/head";
import Layout from "@/components/layout/Layout";
import GenreContainer from "@/components/GenreContainer";
import axios from "axios";

export default function Movies({ genreList }) {
  const { genres } = genreList;
  return (
    <>
      <Head>
        <title>Movies | EntertainHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <Layout>
        <GenreContainer data={genres} category="Movie" />
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {
      genreList: await getMovieGenreList(),
    },
  };
}

async function getMovieGenreList() {
  const moviesEndpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT}/movies/genre`;
  const { data } = await axios.get(moviesEndpoint);
  return data;
}
