import Head from "next/head";
import Layout from "@/components/layout/Layout";
import Trending from "@/components/home/Trending";
import MovieCollections from "@/components/home/MovieCollections";
import axios from "axios";
import TVCollections from "@/components/home/TVCollection";

export default function Home({ shows }) {
  const [trendingData, nowPlayingData, airingTodayData] = shows;

  const movieCollection = [
    {
      title: "Now Playing",
      category: "Movie",
      data: nowPlayingData.nowPlayingShows,
    },
  ];

  const tvCollection = [
    {
      title: "Airing Today",
      category: "TV Series",
      data: airingTodayData.airingTodayShows,
    },
  ];

  return (
    <>
      <Head>
        <title>Home | EntertainHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <Layout>
        <div className="showListContainer ">
          <Trending data={trendingData.trendingShows} />
          <MovieCollections movieCollection={movieCollection} />
          <TVCollections tvCollection={tvCollection} />
        </div>
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {
      shows: await getHomeShows(),
    },
  };
}

async function getHomeShows() {
  const trendingEndpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT}/trending`;
  const nowPlayingEndpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT}/movies/now_playing`;
  const airingTodayEndpoint = `${process.env.NEXT_PUBLIC_API_ENDPOINT}/tvseries/airing_today`;

  const urls = [trendingEndpoint, nowPlayingEndpoint, airingTodayEndpoint];

  const promises = urls.map((url) => axios.get(url));

  try {
    const res = await Promise.all(promises);
    const data = res.map((item) => item.data);
    return data;
  } catch (err) {
    return { error: err };
  }
}
